# Based on https://github.com/simonw/ca-fires-history/blob/main/.github/workflows/scrape.yml
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
   - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.12.0' # Define the elixir version [required]
        otp-version: '24.0' # Define the OTP version [required]
    - name: Install dependencies
      run: mix deps.get
    - name: Fetch latest data
      run: |-
        mix run -e "Hotspotbot.run" | jq . > incidents.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(TZ=Australia/Brisbane date)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push