name: Send message to Telegram channel

on:
  status:

env:
  CHANNEL_NAME: '@QldHotspotUpdates'

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Post message to https://t.me/QldHotspotUpdates
        run: |
          MESSAGE="Contact tracing locations have been updated."
          https://api.telegram.org/bot$TELEGRAM_KEY/sendMessage?chat_id=$CHANNEL_NAME&text=$MESSAGE




